### ISSUE TITLE
Add media entity

### ISSUE THREAD

**Issue by chilic** [PHP-Belarus/php.of.by#33]
We need create `media` entity which will provide function to store and display video/slides and other.

Fields:
* Title (Varchar)
* Embed Code (Text)
* Short Description (Teaser, Text)
* Description (Body, Text)
* Created (Date)
* Published (Boolean)

**Comment by vkhramtsov** [comment]
I think here we need also `edit date` and `publication date`. Because otherwise, you must modify creation date when trying to publish draft. I don't understand purpose of field `Embed Code (Text)`. I think that it is better to use `WYSIWYG` and HTML enabled field for news body, because otherwise we will have a lot of limitations with embedding iframes from youtube, slideshare and other sources.

So my opinion is next:
- Title (Varchar, text only)
- CreateDate (Date, can be invisible in interface, only for maintenance purposes )
- EditDate (Date, can be invisible in interface, only for maintenance purposes)
- PublicationDate (Date, should be visible for admin and on front)
- Short Description (Varchar, html, maximum 255 symbols )
- Description (Text, html)
- Published (Boolean)

**Comment by chilic** [comment]
@vkhramtsov I think we don't need 3 date field.

**Comment by vkhramtsov** [comment]
From my point of view it is better to have these date for maintenance purposes instead of adding them later. We don't need to implement them, we can use doctrine extension, which actually do all things for us.
We need third person to perform final decision.
